osx_image: xcode10
language: objective-c

script:
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-macOS" -sdk macosx clean build
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-macOS" -sdk macosx -enableCodeCoverage YES test
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-iOS" -sdk iphonesimulator -destination name="iPhone 8" clean build
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-iOS" -sdk iphonesimulator -destination name="iPhone 8" -enableCodeCoverage YES test
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV,OS=11.4' clean build
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV,OS=11.4' -enableCodeCoverage YES test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
